package com.hive.agfs.model;

import com.hive.agfs.base.BaseWeiquanxiaofeizhe;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Weiquanxiaofeizhe extends BaseWeiquanxiaofeizhe<Weiquanxiaofeizhe> {
	public static final Weiquanxiaofeizhe dao = new Weiquanxiaofeizhe();
}
